### ISSUE TITLE
v0.2.25 breaks History object

### ISSUE THREAD

**Issue by seoldamiai** [elevenlabs/elevenlabs-python#102]
Using
```
for elevenlabs_history in elevenlabs.History.from_api():
```
I started getting this when I updated to 0.2.25 of elevenlabs package in Python.
```
Traceback (most recent call last):
  File "/home/user/python_projects/history_test.py", line 50, in <module>
    for elevenlabs_history.History.from_api():
  File "/home/user/python_projects/env1/lib/python3.10/site-packages/elevenlabs/api/history.py", line 95, in __iter__
    history_next = self.from_api(
  File "/home/user/python_projects/env1/lib/python3.10/site-packages/elevenlabs/api/history.py", line 84, in from_api
    return cls(**response)
  File "/home/user/python_projects/env1/lib/python3.10/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 88 validation errors for History
history.56.settings.style
  Field required [type=missing, input_value={'similarity_boost': 0.895, 'stability': 0.895}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
history.56.settings.use_speaker_boost
  Field required [type=missing, input_value={'similarity_boost': 0.895, 'stability': 0.895}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
history.57.settings.style
  Field required [type=missing, input_value={'similarity_boost': 0.75, 'stability': 0.895}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
history.57.settings.use_speaker_boost
  Field required [type=missing, input_value={'similarity_boost': 0.75, 'stability': 0.895}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
history.58.settings.style
  Field required [type=missing, input_value={'similarity_boost': 0.75, 'stability': 0.75}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
history.58.settings.use_speaker_boost
  Field required [type=missing, input_value={'similarity_boost': 0.75, 'stability': 0.75}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
```
This problem was not present in 0.2.21.

I've also started getting this:
```
/home/user/python_projects/env1/lib/python3.10/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_id" has conflict with protected namespace "model_".
```

**Comment by flavioschneider** [comment]
Hi @seoldamiai, thanks for reporting. The two issues should be fixed in `v0.2.26`.
