### ISSUE TITLE
type error in streaming in utils.py

### ISSUE THREAD

**Issue by asapsav** [elevenlabs/elevenlabs-python#133]
getting a type error despite `chunk` being a `bytes`. seems like a very basic issue that should not happen, appreciate any help resolving/pointing me to an obvious mistake on my side

code:
```python
audio_stream = generate("Hello world", voice = 'skull_0', stream=True)  
for chunk in audio_stream:
    print(type(chunk))
    stream(chunk)
```

error:
```
<class 'bytes'>
Traceback (most recent call last):
  File "/Users/saveliykholin/Documents/skull-gpt/11labs-streaming.py", line 17, in <module>
    stream(chunk)
  File "/usr/local/lib/python3.11/site-packages/elevenlabs/utils.py", line 76, in stream
    mpv_process.stdin.write(chunk)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'int'
```

**Comment by IdkwhatImD0ing** [comment]
Should be stream(audio_stream)

**Comment by majumba** [comment]
thta was a but frustrating - seems like docs could get cleaned up
