### ISSUE TITLE
Unable to import elevenlabs

### ISSUE THREAD

**Issue by jstremme** [elevenlabs/elevenlabs-python#15]
After `pip install elevenlabs==0.2.9` and opening Python 3.8,

```
from elevenlabs import generate
```

gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/delphi/lib/python3.8/site-packages/elevenlabs/__init__.py", line 1, in <module>
    from .api import *  # noqa F403
  File "/opt/anaconda3/envs/delphi/lib/python3.8/site-packages/elevenlabs/api/__init__.py", line 2, in <module>
    from .history import *  # noqa F403
  File "/opt/anaconda3/envs/delphi/lib/python3.8/site-packages/elevenlabs/api/history.py", line 9, in <module>
    from .voice import VoiceSettings
  File "/opt/anaconda3/envs/delphi/lib/python3.8/site-packages/elevenlabs/api/voice.py", line 21, in <module>
    class VoiceClone(API):
  File "pydantic/main.py", line 178, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    """Special type construct to mark class variables.
  File "/opt/anaconda3/envs/delphi/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/opt/anaconda3/envs/delphi/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

**Comment by flavioschneider** [comment]
Updating to python 3.9 should solve it

**Comment by jstremme** [comment]
`0.2.10` doesn't work with Py38 unfortunately but upgrading to Py39 did the trick.  Thanks!

**Comment by donasan** [comment]
Is there an elevenlabs version that works with python 3.8? Unfortunately I cannot upgrade python (too many other dependencies) on my system and cannot get it to work :(

**Comment by jstremme** [comment]
> Is there an elevenlabs version that works with python 3.8? Unfortunately I cannot upgrade python (too many other dependencies) on my system and cannot get it to work :(

I'm finding it hard to upgrade my project as well :) @flavioschneider, curious if Py38 compatibility would be easy for you guys.  Thanks in either case for the nice package!

**Comment by seanroades** [comment]
I am using Python 3.9.12 and elevenlabs 0.2.10 and it doesn't import

**Comment by mrteey** [comment]
> I am using Python 3.9.12 and elevenlabs 0.2.10 and it doesn't import

What error are you getting?

**Comment by flavioschneider** [comment]
Python 3.8 support has been added in `v0.2.13`!
