### ISSUE TITLE
Connection Timeout w/2418 characters?

### ISSUE THREAD

**Issue by RevelryMedia** [elevenlabs/elevenlabs-python#229]
My code successfully reads the file for the text, it generates the audio on Elevenlabs (I can see it on the website), but doesn't return the audio before I get a timeout error. The text length is 396 words/ 2418 characters. This code does run and return a file when I cut it down to a single sentence in the text file. _(I tried updating to 1.0.1 and it persists.)_

I believe I'm within the limits of the api requests and was told in Discord I shouldn't get a timeout in the python library??? **This one is a little more frustrating as I burned a lot of credits trying to get it to work** because it does execute on the Elevenlabs side...

### Script:
`from elevenlabs import save, play
from elevenlabs.client import ElevenLabs
from app_secrets import get_secrets

elevenlabs_api_key = get_secrets("ElevenlabsKey")

client = ElevenLabs(
    api_key=elevenlabs_api_key, 
)

with open('news_segment_20240323_003009/news/news_script.txt', 'r') as file:
    anchor_script = file.read()

audio_path = "news_segment_20240323_003009" + "/anchor_voice.mp3"
print("script " + anchor_script)
audio = client.generate(
    text= anchor_script, 
    voice="Michael",
    model="eleven_multilingual_v2",
)
play(audio)
save(audio, audio_path) # TODO change file `

### Error:
`Traceback (most recent call last):
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_sync\connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_sync\http11.py", line 143, in handle_request
    raise exc
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_sync\http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_sync\http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_sync\http11.py", line 224, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_backends\sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "C:\Users\Default.DESKTOP-J1CIEQC\miniconda3\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\dev\aiVideoStream\testeleven.py", line 21, in <module>
    play(audio)
  File "C:\dev\Environments\aivideo\Lib\site-packages\elevenlabs\play.py", line 19, in play
    audio = b"".join(audio)
            ^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\elevenlabs\text_to_speech\client.py", line 106, in convert
    with self._client_wrapper.httpx_client.stream(
  File "C:\Users\Default.DESKTOP-J1CIEQC\miniconda3\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\elevenlabs\core\http_client.py", line 104, in stream
    with self.httpx_client.stream(*args, **kwargs) as stream:
  File "C:\Users\Default.DESKTOP-J1CIEQC\miniconda3\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_client.py", line 870, in stream
    response = self.send(
               ^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\Default.DESKTOP-J1CIEQC\miniconda3\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\dev\Environments\aivideo\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out`

**Comment by dsinghvi** [comment]
Hey @RevelryMedia, apologize for the frustrating use of the Python library. Have you tried setting the `timeout` [flag](https://github.com/elevenlabs/elevenlabs-python/blob/44e805e8f9c3d50ec951166b173d7c47a4143e4d/src/elevenlabs/client.py#L55)? 

Specifically if you type it as `None` we'll remove any sort of timeout.

**Comment by RevelryMedia** [comment]
> Hey @RevelryMedia, apologize for the frustrating use of the Python library. Have you tried setting the `timeout` [flag](https://github.com/elevenlabs/elevenlabs-python/blob/44e805e8f9c3d50ec951166b173d7c47a4143e4d/src/elevenlabs/client.py#L55)?
> 
> Specifically if you type it as `None` we'll remove any sort of timeout.

Maybe I'm not doing it right(see below), I tried None and that still timed out, in the ElevenLabs Class doc string I can see it says None = 60, so maybe it's just going to 60? I then tried 1000 and even 1000000 and it times out as well. Blowing a lot of credits on this now... 

`client = ElevenLabs(
    api_key=elevenlabs_api_key, # Defaults to ELEVEN_API_KEY,
    timeout=1000000
)`

**Comment by dsinghvi** [comment]
@RevelryMedia this bug has been fixed in `v1.0.2`. Please re-open the issue if you still encounter any issues and sorry for any inconvenience.

**Comment by LovanDog** [comment]
had a similar problem. as mentioned, update to 1.0.2 and setting longer timeout in client helped :)

**Comment by calymera** [comment]
> @RevelryMedia this bug has been fixed in `v1.0.2`. Please re-open the issue if you still encounter any issues and sorry for any inconvenience.

i'm using elevenlabs. api in make.com automation and getting this error - The operation was completed with a warning. The operation timed out
with 60 sentenses long, 20 is ok, how can i fix that?
