### ISSUE TITLE
Langchain instructions give errors about missing generate() method

### ISSUE THREAD

**Issue by mspertus** [elevenlabs/elevenlabs-python#244]
When I follow the instructions for using the langchain Eleven Labs Text2SpeechTool [here](https://python.langchain.com/docs/integrations/tools/eleven_labs_tts), I get the following error.
```Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from langchain_community.tools import ElevenLabsText2SpeechTool
>>>
>>> text_to_speak = "Hello world! I am the real slim shady"
>>>
>>> tts = ElevenLabsText2SpeechTool()
>>> speech_file = tts.run(text_to_speak)
Traceback (most recent call last):
  File "C:\Users\mike\anaconda3\envs\baseClone\Lib\site-packages\langchain_community\tools\eleven_labs\text2speech.py", line 58, in _run
    speech = elevenlabs.generate(text=query, model=self.model)
             ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'elevenlabs' has no attribute 'generate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mike\anaconda3\envs\baseClone\Lib\site-packages\langchain_core\tools.py", line 422, in run
    raise e
  File "C:\Users\mike\anaconda3\envs\baseClone\Lib\site-packages\langchain_core\tools.py", line 381, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "C:\Users\mike\anaconda3\envs\baseClone\Lib\site-packages\langchain_community\tools\eleven_labs\text2speech.py", line 65, in _run
    raise RuntimeError(f"Error while running ElevenLabsText2SpeechTool: {e}")
RuntimeError: Error while running ElevenLabsText2SpeechTool: module 'elevenlabs' has no attribute 'generate'
```
My langchain package versions are langchain-0.1.14, langchain-community-0.0.31, langchain-core-0.1.38, langchain-text-splitters-0.0.1 langsmith-0.1.38 and my elevenlabs version is 1.0.3. I believe I followed the instructions in the langchain docs above correctly.

Any advice appreciated,
Mike

**Comment by dsinghvi** [comment]
@mspertus it looks like langchain hasn't upgraded to v1.x of the SDK (there were some breaks from v0.x to v1.x).

**Comment by HelloKevinChen** [comment]
You can lower the version of elevenlabs to below 1.0.  I have tried multiple times and found that the properties have not been changed above 1. x
example:  pip install --upgrade elevenlabs==0.2.27,  it's workful for me.

**Comment by baiziyuandyufei** [comment]
the same issuse

**Comment by Pavun-KumarCH** [comment]
This Issue Still persists, @HelloKevinChen  Thanks for your tip; it's workful worked for me.
example: pip install --upgrade elevenlabs==0.2.27,

**Comment by AngeloGiacco** [comment]
i'm closing this issue as it is not an issue with our SDK, but with langchain
