### ISSUE TITLE
Does not work on python 3.7

### ISSUE THREAD

**Issue by rogeriochaves** [elevenlabs/elevenlabs-python#28]
Hello there, I'm trying to use elevenlabs on my raspberry python, using python 3.7 cuz that's the only version where numpy works out of the box for raspberry

But unfortunately, it throws a typing error:

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import lib.elevenlabs as elevenlabs
  File "/home/pi/Projects/bmo/lib/elevenlabs.py", line 7, in <module>
    from elevenlabs import generate, Voice, VoiceSettings
  File "/home/pi/.local/lib/python3.7/site-packages/elevenlabs/__init__.py", line 2, in <module>
    from .simple import *  # noqa F403
  File "/home/pi/.local/lib/python3.7/site-packages/elevenlabs/simple.py", line 101, in <module>
    ) -> Union[bytes, Iterator[bytes]]:
TypeError: 'ABCMeta' object is not subscriptable
```

I think should be easily fixable, let me try to send a PR

**Comment by rogeriochaves** [comment]
oh, nvm, I see that on the latest version it's already fixed, cheers :)
