### ISSUE TITLE
Python SDK - Get method failure

### ISSUE THREAD

**Issue by cahyosubroto** [elevenlabs/elevenlabs-python#286]
Hi @lharries 

The get method in the projects module fails during the unpacking response from the server. 

Here are steps to reproduce:

1. In Evelenlabs python SDK, Create a project
2. Get project by id

`client = ElevenLabs(api_key="<your api key>")

add_project_response = client.projects.add(
        name="example",
        default_model_id="eleven_multilingual_v2",
        default_title_voice_id="21m00Tcm4TlvDq8ikWAM",
        default_paragraph_voice_id="21m00Tcm4TlvDq8ikWAM"
)

project_info = client.projects.get(add_project_response.project.project_id)`

Here's the error log:

`Traceback (most recent call last):
  File "xxx\elevenlabs-examples\examples\projects\python\main.py", line 141, in <module>
    main()
  File "xxx\elevenlabs-examples\examples\projects\python\main.py", line 94, in main
    project_info = client.projects.get(project_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\elevenlabs-examples\examples\projects\python\venv\Lib\site-packages\elevenlabs\projects\client.py", line 263, in get
    return typing.cast(ProjectExtendedResponseModel, construct_type(type_=ProjectExtendedResponseModel, object_=_response.json()))  # type: ignore
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\elevenlabs-examples\examples\projects\python\venv\Lib\site-packages\elevenlabs\core\unchecked_base_model.py", line 171, in construct_type
    return type_.construct(**object_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\elevenlabs-examples\examples\projects\python\venv\Lib\site-packages\elevenlabs\core\unchecked_base_model.py", line 62, in construct
    return [construct_type(object_=entry, type_=inner_type) for entry in object_]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\elevenlabs-examples\examples\projects\python\venv\Lib\site-packages\elevenlabs\core\unchecked_base_model.py", line 171, in construct_type
    return type_.construct(**object_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\elevenlabs-examples\examples\projects\python\venv\Lib\site-packages\elevenlabs\core\unchecked_base_model.py", line 62, in construct
    fields_values[name] = construct_type(object_=values[key], type_=type_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\elevenlabs-examples\examples\projects\python\venv\Lib\site-packages\elevenlabs\core\unchecked_base_model.py", line 171, in construct_type
    return type_.construct(**object_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: elevenlabs.core.unchecked_base_model.UncheckedBaseModel.construct() argument after ** must be a mapping, not NoneType`

ElevenLabs Python SDK version: 1.2.1

**Comment by dsinghvi** [comment]
@cahyosubroto thanks for reporting this issue, we will follow up and get back to you.

**Comment by dsinghvi** [comment]
@cahyosubroto this is now fixed in `v1.2.2`
