### ISSUE TITLE
Stream is not working in production

### ISSUE THREAD

**Issue by muhammad-grayphite** [elevenlabs/elevenlabs-python#338]
I am using Streaming and I have deployed the app on [huggingface](https://huggingface.co/), here is the code 
```   
audio = elevenlabs_client.generate(
        text=text,
        voice="Adam",
        model="eleven_turbo_v2_5",
        stream=True,
        optimize_streaming_latency=3
    )
 stream(audio)
```

but for some reason getting this error in stream function

```Matplotlib created a temporary cache directory at /tmp/matplotlib-2t1yp2__ because the default path (/usr/src/app/tmp/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Exception in thread Thread-7 (text_to_speech_file):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/caller_v2.py", line 35, in text_to_speech_file
    stream(audio)
  File "/usr/local/lib/python3.10/site-packages/elevenlabs/play.py", line 91, in stream
    mpv_process.stdin.flush()  # type: ignore
BrokenPipeError: [Errno 32] Broken pipe
```

Things to considered I have installed all the spendencies and packages it required like mpv, ffmpeg
<img width="1423" alt="Screenshot 2024-08-07 at 2 58 59 AM" src="https://github.com/user-attachments/assets/4b4f71e4-f7bf-40d6-a0e6-c08f5cd6a1ef">

**Comment by muhammad-grayphite** [comment]
Hello any update on this? Anyone??

**Comment by AngeloGiacco** [comment]
hi! please can you update this issue as i believe this is no longer an issue and there is not much information to go off. in the meantime i am closing the issue, but please reopen if you have more information
