### ISSUE TITLE
Not Getting Signed URL

### ISSUE THREAD

**Issue by Niteshiya** [elevenlabs/elevenlabs-python#407]
### Description

[**Used the basic conversational agent**](https://github.com/elevenlabs/elevenlabs-examples/blob/main/examples/conversational-ai/python/convai/demo.py)

Error: 
```
Traceback (most recent call last):
  File "/Users/homeos/nitesh/act_reporter/mytest.py", line 64, in <module>
    main()
  File "/Users/homeos/nitesh/act_reporter/mytest.py", line 55, in main
    conversation.start_session()
  File "/Users/homeos/nitesh/act_reporter/venv/lib/python3.12/site-packages/elevenlabs/conversational_ai/conversation.py", line 128, in start_session
    ws_url = self._get_signed_url() if self.requires_auth else self._get_wss_url()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/homeos/nitesh/act_reporter/venv/lib/python3.12/site-packages/elevenlabs/conversational_ai/conversation.py", line 237, in _get_signed_url
    return response.json()["signed_url"]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'signed_url'
```

**Comment by Niteshiya** [comment]
@dsinghvi  Please help if possible

**Comment by dsinghvi** [comment]
@Niteshiya this should be fixed on the latest minor. Can you confirm?

**Comment by Niteshiya** [comment]
@dsinghvi 
I resolved the issue with a small change in the code. Initially, the method was written as follows:
File : venv/lib/python3.12/site-packages/elevenlabs/conversational_ai/conversation.py
```
def _get_signed_url(self):
        
        response = self.client.get_signed_url(agent_id=self.agent_id)
        return response.signed_url
```
However, this was incorrectly referencing the Eleven Labs client, which doesn’t have a get_signed_url method.
the corrected version 
```
def _get_signed_url(self):  
    response = self.client.conversational_ai.get_signed_url(agent_id=self.agent_id)  
    return response.signed_url
```
By properly directing the call to conversational_ai, the issue is resolved, and the method works as expected. Please add this to code .
