### ISSUE TITLE
Issue with ffmpeg missing

### ISSUE THREAD

**Issue by bsullins** [elevenlabs/elevenlabs-python#44]
Attempting a simple script to generate a voice and receiving the error below. Using pyCharm on MacOS for reference.

```from elevenlabs import generate, play
from elevenlabs import set_api_key

set_api_key("abc123")

audio = generate(
  text="Hi! My name is Ben, nice to meet you!",
  voice="myvoiceid",
  model="eleven_monolingual_v1"
)

play(audio)```


###error
```/Users/bensullins/PycharmProjects/gptLearn/venv/bin/python /Users/bensullins/PycharmProjects/gptLearn/makeVoice.py 
Traceback (most recent call last):
  File "/Users/bensullins/PycharmProjects/gptLearn/makeVoice.py", line 12, in <module>
    play(audio)
  File "/Users/bensullins/PycharmProjects/gptLearn/venv/lib/python3.10/site-packages/elevenlabs/utils.py", line 24, in play
    raise ValueError("ffplay from ffmpeg not found, necessary to play audio.")
ValueError: ffplay from ffmpeg not found, necessary to play audio.```

**Comment by flavioschneider** [comment]
Did you install ffmpeg? It's necessary to play audio.

**Comment by bsullins** [comment]
I did ```pip install ffmpeg``` but apparently that wasn't it! the Brew command worked, thanks!

**Comment by ThatFlint** [comment]
> Did you install ffmpeg? It's necessary to play audio. `brew install ffmpeg`

I'm working on windows with pycharm, and I believe I've managed to install brew, but I still cannot run the command in the pycharm terminal. Do you know how I could get this to work?
