### ISSUE TITLE
Elevenlabs seems to loose connection to API

### ISSUE THREAD

**Issue by Fummelfeldagent** [elevenlabs/elevenlabs-python#52]
it works for the first couple of minutes on telegram but then it looses connection to elevenlabs api i guess?! by running a speach to speach bot via Elevenlabs I run into an error:

ERROR:root:REQUEST THAT CAUSED THE ERROR:
-----------START-----------
POST https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM/stream
User-Agent: python-requests/2.31.0
Accept-Encoding: gzip, deflate
accept: */*
Connection: keep-alive
xi-api-key: XOXO
Content-Length: 101
Content-Type: application/json

b'{"text": "Ja, mein Meister. Ich bin immer hier, um zu helfen. Wie kann ich Ihnen heute assistieren?"}'
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\telegram\ext\dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\telegram\ext\handler.py", line 145, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\XOXO\Jason2\02_elevenlabs_chatbot.py", line 30, in text_message
    response_byte_audio = voice.generate_audio_bytes(response_text)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\elevenlabslib\ElevenLabsVoice.py", line 117, in generate_audio_bytes
    response = _api_json("/text-to-speech/" + self._voiceID + "/stream", self._linkedUser.headers, jsonData=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\elevenlabslib\helpers.py", line 46, in _api_json
    return _api_call("json",path, headers, jsonData)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\elevenlabslib\helpers.py", line 37, in _api_call
    raise e
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\elevenlabslib\helpers.py", line 33, in _api_call
    response.raise_for_status()
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM/stream
ERROR:root:REQUEST THAT CAUSED THE ERROR:
-----------START-----------
POST https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM/stream
User-Agent: python-requests/2.31.0
Accept-Encoding: gzip, deflate
accept: */*
Connection: keep-alive
xi-api-key: XOXO
Content-Length: 102
Content-Type: application/json

b'{"text": "Ja, mein Meister. Ich bin immer hier, um Ihnen zu dienen. Wie kann ich Ihnen weiterhelfen?"}'
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\telegram\ext\dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\telegram\ext\handler.py", line 145, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\XOXO\Jason2\02_elevenlabs_chatbot.py", line 30, in text_message
    response_byte_audio = voice.generate_audio_bytes(response_text)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\elevenlabslib\ElevenLabsVoice.py", line 117, in generate_audio_bytes
    response = _api_json("/text-to-speech/" + self._voiceID + "/stream", self._linkedUser.headers, jsonData=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\elevenlabslib\helpers.py", line 46, in _api_json
    return _api_call("json",path, headers, jsonData)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\elevenlabslib\helpers.py", line 37, in _api_call
    raise e
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\elevenlabslib\helpers.py", line 33, in _api_call
    response.raise_for_status()
  File "C:\Users\XOXO\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM/stream

can provide original code if needed

**Comment by flavioschneider** [comment]
Yes the original code would be helpful.
