### ISSUE TITLE
Pydantic errors

### ISSUE THREAD

**Issue by PeteInBrissie** [elevenlabs/elevenlabs-python#65]
Raspberry Pi Lite 64 Bit.

I have started from scratch and updated so many times, have run Bump Pydantic over the whole setup - the issue persists.

Any help appreciated. Thanks.

/home/pete/.local/lib/python3.9/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/pete/bmo/main.py", line 17, in <module>
    from lib.chatgpt import ChatGPT, Conversation, Message, initial_message
  File "/home/pete/bmo/lib/chatgpt.py", line 11, in <module>
    from lib.text_to_speech import TextToSpeech
  File "/home/pete/bmo/lib/text_to_speech/__init__.py", line 6, in <module>
    from lib.text_to_speech.elevenlabs_api import ElevenLabsAPI
  File "/home/pete/bmo/lib/text_to_speech/elevenlabs_api.py", line 11, in <module>
    from elevenlabs import generate, Voice, VoiceSettings
  File "/home/pete/.local/lib/python3.9/site-packages/elevenlabs/__init__.py", line 1, in <module>
    from .api import *  # noqa F403
  File "/home/pete/.local/lib/python3.9/site-packages/elevenlabs/api/__init__.py", line 2, in <module>
    from .history import *  # noqa F403
  File "/home/pete/.local/lib/python3.9/site-packages/elevenlabs/api/history.py", line 9, in <module>
    from .voice import VoiceSettings
  File "/home/pete/.local/lib/python3.9/site-packages/elevenlabs/api/voice.py", line 30, in <module>
    class VoiceClone(API):
  File "/home/pete/.local/lib/python3.9/site-packages/elevenlabs/api/voice.py", line 38, in VoiceClone
    def computed_files_tuple(cls, values) -> List[str]:
  File "/home/pete/.local/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "/home/pete/.local/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0.3/u/root-validator-pre-skip

**Comment by PeteInBrissie** [comment]
Fixed by downgrading to Pydantic 1.10
