### ISSUE TITLE
Can't Input Stream

### ISSUE THREAD

**Issue by jryebread** [elevenlabs/elevenlabs-python#76]
Trying to do input streaming but getting an error about the generate function not taking a generator, here's my code, need some help (might have some mistakes)

It would be great to get an example of how to stream chunks from openai

```

Traceback (most recent call last):
  File "/home/snowy/miniconda3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/snowy/miniconda3/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/snowy/eveScamBait/llm_convo/main.py", line 44, in run_chat
    run_conversation(agent_a, agent_b)
  File "/home/snowy/eveScamBait/llm_convo/llm_convo/conversation.py", line 7, in run_conversation
    text_a = agent_a.get_response(transcript)
  File "/home/snowy/eveScamBait/llm_convo/llm_convo/agents.py", line 61, in get_response
    response = self.openai_chat.get_response(transcript)
  File "/home/snowy/eveScamBait/llm_convo/llm_convo/openai_io.py", line 46, in get_response
    for chunk in audio_stream:
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/elevenlabs/api/tts.py", line 38, in generate_stream
    response = API.post(url, json=data, stream=True, api_key=api_key)
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/elevenlabs/api/base.py", line 65, in post
    return API.request(url, method="post", *args, **kwargs)  # type: ignore
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/elevenlabs/api/base.py", line 35, in request
    response = requests.post(url, headers=headers, **kwargs)
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/home/snowy/miniconda3/lib/python3.9/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/home/snowy/miniconda3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/snowy/miniconda3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/snowy/miniconda3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/snowy/miniconda3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
```

```
class OpenAIChatCompletion:
    def __init__(self, system_prompt: str, session):
        self.system_prompt = system_prompt
        self.session = session

    def get_response(self, transcript: List[str]) -> str:
        messages = [
            {"role": "system", "content": self.system_prompt},
        ]
        for i, text in enumerate(reversed(transcript)):
            messages.insert(1, {"role": "user" if i % 2 == 0 else "assistant", "content": text})

        # Create a generator for the chat completion
        def chat_stream():
            for chunk in openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=messages,
                stream=True,
            ):
                content = chunk["choices"][0].get("delta", {}).get("content")
                if content is not None:
                    yield content

        # Generate the audio stream from the chat completion
        audio_stream = generate(
            text=chat_stream(),
            voice="Bella",
            model="eleven_monolingual_v1",
            stream=True
        )

        # Play the audio stream as soon as chunks are available
        text_chunks = []
        for chunk in audio_stream:
            text_chunks.append(chunk)
            self.session.play(chunk)

        # Return the text that was said
        return ' '.join(text_chunks)


```

**Comment by flavioschneider** [comment]
Did you update to the latest version `pip install elevenlabs -U`? Input streaming was released in `v.0.2.22`
