### ISSUE TITLE
Error When I'm Trying to Access the Import set_api_key, generate or play modules

### ISSUE THREAD

**Issue by NeoDaenium** [elevenlabs/elevenlabs-python#9]
Hi Team, I'm having this issue whenever Im trying to access
the set_api_key, generate or play modules:

Traceback (most recent call last):
  File "pyper.py", line 1, in <module>
    from elevenlabs import set_api_key
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python38\lib\site-packages\elevenlabs\__init__.py", line 1, in <module>
    from .api import *  # noqa F403
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python38\lib\site-packages\elevenlabs\api\__init__.py", line 2, in <module>
    from .history import *  # noqa F403
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python38\lib\site-packages\elevenlabs\api\history.py", line 9, in <module>
    from .voice import VoiceSettings
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python38\lib\site-packages\elevenlabs\api\voice.py", line 21, in <module>
    class VoiceClone(API):
  File "pydantic\main.py", line 178, in pydantic.main.ModelMetaclass.__new__
    
  File "pydantic\typing.py", line 399, in pydantic.typing.resolve_annotations
    """Special type construct to mark class variables.
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python38\lib\typing.py", line 270, in 
_eval_type
    return t._evaluate(globalns, localns)
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python38\lib\typing.py", line 518, in 
_evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable

Not sure if some of my modules are outdated, but I would appreciate some guidance on what I can do to make it work.
My Python version is 3.8.10
Is my Python version outdated, or is it my other modules?

It seems to work fine in Google collab. Thanks.

**Comment by flavioschneider** [comment]
This package has only been tested for python versions >= 3.9. Could you try updating?
